// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	da "github.com/celestiaorg/rollmint/da"
	mock "github.com/stretchr/testify/mock"
)

// BlockRetriever is an autogenerated mock type for the BlockRetriever type
type BlockRetriever struct {
	mock.Mock
}

// RetrieveBlocks provides a mock function with given fields: dataLayerHeight
func (_m *BlockRetriever) RetrieveBlocks(dataLayerHeight uint64) da.ResultRetrieveBlocks {
	ret := _m.Called(dataLayerHeight)

	var r0 da.ResultRetrieveBlocks
	if rf, ok := ret.Get(0).(func(uint64) da.ResultRetrieveBlocks); ok {
		r0 = rf(dataLayerHeight)
	} else {
		r0 = ret.Get(0).(da.ResultRetrieveBlocks)
	}

	return r0
}

type mockConstructorTestingTNewBlockRetriever interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlockRetriever creates a new instance of BlockRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlockRetriever(t mockConstructorTestingTNewBlockRetriever) *BlockRetriever {
	mock := &BlockRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
