// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	p2p "github.com/celestiaorg/rollmint/p2p"
	mock "github.com/stretchr/testify/mock"
)

// GossiperOption is an autogenerated mock type for the GossiperOption type
type GossiperOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *GossiperOption) Execute(_a0 *p2p.Gossiper) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*p2p.Gossiper) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGossiperOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewGossiperOption creates a new instance of GossiperOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGossiperOption(t mockConstructorTestingTNewGossiperOption) *GossiperOption {
	mock := &GossiperOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
