// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	abcitypes "github.com/tendermint/tendermint/abci/types"

	mock "github.com/stretchr/testify/mock"

	types "github.com/tendermint/tendermint/types"
)

// PostCheckFunc is an autogenerated mock type for the PostCheckFunc type
type PostCheckFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *PostCheckFunc) Execute(_a0 types.Tx, _a1 *abcitypes.ResponseCheckTx) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Tx, *abcitypes.ResponseCheckTx) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPostCheckFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostCheckFunc creates a new instance of PostCheckFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostCheckFunc(t mockConstructorTestingTNewPostCheckFunc) *PostCheckFunc {
	mock := &PostCheckFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
