// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	v1 "github.com/celestiaorg/rollmint/mempool/v1"
	mock "github.com/stretchr/testify/mock"
)

// TxMempoolOption is an autogenerated mock type for the TxMempoolOption type
type TxMempoolOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *TxMempoolOption) Execute(_a0 *v1.TxMempool) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewTxMempoolOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxMempoolOption creates a new instance of TxMempoolOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxMempoolOption(t mockConstructorTestingTNewTxMempoolOption) *TxMempoolOption {
	mock := &TxMempoolOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
